### ISSUE TITLE
Please provide AppImage for Linux on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [Kthulu120/mangle#4]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

`electron-builder` has support for generating AppImages out of the box. In fact, it is already configured in this project:

https://github.com/Kthulu120/mangle/blob/b3f2b2079917a6f6f422537732fa5200fba05963/package.json#L69

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by Kthulu120** [comment]
Updated the latest release with an AppImage, accidentally forgot it.

**Comment by probonopd** [comment]
Thank you.
